# **Topic : Introduction to Multi-Layer Perceptron**

## **Objective for this template:**
1. To understand the basic steps needed to define a Multi-layer Perceptron in scikit-learn
2. To demonstrate how the basic MLP prediction model works
3. To practice building a basic deployment interface for the MLP prediction model

Designed By: Rodolfo C. Raga Jr. Copyright @2021

__Permission granted to use template for educational purposes so long as this heading is not removed.__
---

## Step 1. 
Declare and import all needed libraries

## Step 2. 
Declare class categories for use in categorically classifying the prediction output

In [83]:
# Let's start by naming the class categories



## Step 3. 
Read the dataset and inspect its characteristics

In [4]:
# Reading the dataset through a Pandas function
df = pd.read_csv('E:/My Documents/Files (1st Sem 2021-2022)/Research/Training - DataScience and DL workshop/datasets/Fish_Species.csv')



            Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000
<bound method NDFrame.head of     Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3  

## Step 4. 
Extract Feature matrix and target array.
The fish dataset has seven columns. 
The task is to predict the class (which are the species in the first column) that a fish belongs to.

In [5]:
# Extract feature matrix and assign to variable "X"

# Extract target and assign them to variable "Y". Object dtype refers to strings.
 

## Step 5.1. 
Apply first preprocessing  for testing later. In this case, Normalization using the MinMax Scale.

In [147]:
from sklearn.preprocessing import MinMaxScaler


#Convert the list to a NumPy array


#Normalize the vector


Raw data form:
 [[2.42000e+02 2.32000e+01 2.54000e+01 3.00000e+01 1.15200e+01 4.02000e+00
  2.90000e+02 2.40000e+01 2.63000e+01 3.12000e+01 1.24800e+01 4.30560e+00
  3.40000e+02 2.39000e+01 2.65000e+01 3.11000e+01 1.23778e+01 4.69610e+00
  3.63000e+02 2.63000e+01 2.90000e+01 3.35000e+01 1.27300e+01 4.45550e+00
  4.30000e+02 2.65000e+01 2.90000e+01 3.40000e+01 1.24440e+01 5.13400e+00
  4.50000e+02 2.68000e+01 2.97000e+01 3.47000e+01 1.36024e+01 4.92740e+00
  5.00000e+02 2.68000e+01 2.97000e+01 3.45000e+01 1.41795e+01 5.27850e+00
  3.90000e+02 2.76000e+01 3.00000e+01 3.50000e+01 1.26700e+01 4.69000e+00
  4.50000e+02 2.76000e+01 3.00000e+01 3.51000e+01 1.40049e+01 4.84380e+00
  5.00000e+02 2.85000e+01 3.07000e+01 3.62000e+01 1.42266e+01 4.95940e+00
  4.75000e+02 2.84000e+01 3.10000e+01 3.62000e+01 1.42628e+01 5.10420e+00
  5.00000e+02 2.87000e+01 3.10000e+01 3.62000e+01 1.43714e+01 4.81460e+00
  5.00000e+02 2.91000e+01 3.15000e+01 3.64000e+01 1.37592e+01 4.36800e+00
  3.40000e+02 2.95000e

## Step 5.2. 
Apply 2nd preprocessing  for testing later. In this case, Standarization using the StandardScaler.

In [148]:
from sklearn.preprocessing import StandardScaler 
X.head()

#Convert the list to a NumPy array


#Standardize the matrix




Raw data form:
 [[2.42000e+02 2.32000e+01 2.54000e+01 3.00000e+01 1.15200e+01 4.02000e+00
  2.90000e+02 2.40000e+01 2.63000e+01 3.12000e+01 1.24800e+01 4.30560e+00
  3.40000e+02 2.39000e+01 2.65000e+01 3.11000e+01 1.23778e+01 4.69610e+00
  3.63000e+02 2.63000e+01 2.90000e+01 3.35000e+01 1.27300e+01 4.45550e+00
  4.30000e+02 2.65000e+01 2.90000e+01 3.40000e+01 1.24440e+01 5.13400e+00
  4.50000e+02 2.68000e+01 2.97000e+01 3.47000e+01 1.36024e+01 4.92740e+00
  5.00000e+02 2.68000e+01 2.97000e+01 3.45000e+01 1.41795e+01 5.27850e+00
  3.90000e+02 2.76000e+01 3.00000e+01 3.50000e+01 1.26700e+01 4.69000e+00
  4.50000e+02 2.76000e+01 3.00000e+01 3.51000e+01 1.40049e+01 4.84380e+00
  5.00000e+02 2.85000e+01 3.07000e+01 3.62000e+01 1.42266e+01 4.95940e+00
  4.75000e+02 2.84000e+01 3.10000e+01 3.62000e+01 1.42628e+01 5.10420e+00
  5.00000e+02 2.87000e+01 3.10000e+01 3.62000e+01 1.43714e+01 4.81460e+00
  5.00000e+02 2.91000e+01 3.15000e+01 3.64000e+01 1.37592e+01 4.36800e+00
  3.40000e+02 2.95000e

## Step 6. 
Inspect target array and convert to numeriic encoded form

In [149]:
# Now transforming categorial into numerical values



# Fit the labels




Target Array
Raw Categorical Form: [['Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
  'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
  'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
  'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Roach'
  'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
  'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
  'Roach' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish'
  'Whitefish' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki'
  'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Perch' 'Perch' 'Perch'
  'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
  'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
  'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
  'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
  'Perch' 'Perch

c:\Users\Jundy\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


## Step 7. 
Generate training and validation datasets

In [171]:
# Now for train and test split (80% of  dataset into  training set and  other 20% into test data)




Total Testing data 32 records
[2 2 3 0 0 4 2 1 4 1 2 2 0 5 0 1 6 0 3 5 3 2 5 2 0 2 0 5 3 5 2 2]


## Step 8. 
Instantiate prediction model and with fit with training data.

In [172]:
# Finally for the MLP- Multilayer Perceptron




c:\Users\Jundy\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

## Step 9. 
Validate prediction model performance using testing data.

In [173]:





# Last thing: evaluation of MLP algorithm performance in classifying fish species



Actual Species: [2 2 3 0 0 4 2 1 4 1 2 2 0 5 0 1 6 0 3 5 3 2 5 2 0 2 0 5 3 5 2 2]
Predicted Species: [4 2 3 0 0 4 5 1 4 1 2 2 0 5 0 1 2 0 3 5 3 2 5 2 0 5 0 5 3 5 2 2]

Confusion Matrix
 [[7 0 0 0 0 0 0]
 [0 3 0 0 0 0 0]
 [0 0 7 0 1 2 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 2 0 0]
 [0 0 0 0 0 5 0]
 [0 0 1 0 0 0 0]]

Summary Performance Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         3
           2       0.88      0.70      0.78        10
           3       1.00      1.00      1.00         4
           4       0.67      1.00      0.80         2
           5       0.71      1.00      0.83         5
           6       0.00      0.00      0.00         1

    accuracy                           0.88        32
   macro avg       0.75      0.81      0.77        32
weighted avg       0.86      0.88      0.86        32



c:\Users\Jundy\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Jundy\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Jundy\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Step 10. 

Model Deployment. Your task is to design and implement a basic deployment interface for this prediction model.

In [120]:
prediction =  mlp.predict(np.array([[242.0, 23.2, 25.4, 30.0, 11.5200, 4.0200]]))
print(species_names[prediction[0]])

Bream
